export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_ERROR_HANDLER = 'SET_ERROR_HANDLER';

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const DESTROY_AUTH_TOKEN = 'DESTROY_AUTH_TOKEN';

export const SET_LAYOUT_STATE = 'SET_LAYOUT_STATE';